rabbit_up:
	docker compose -f docker-compose.rabbit.yml up -d
rabbit_down:
	docker compose -f docker-compose.rabbit.yml down
emqx_up:
	docker compose -f docker-compose.emqx.yml up -d
emqx_down:
	docker compose -f docker-compose.emqx.yml down